FROM node:22-alpine

WORKDIR /src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

ENV VITE_APP_NEWS_API_KEY=$VITE_APP_NEWS_API_KEY
ENV VITE_APP_GUARDIAN_API_KEY=$VITE_APP_GUARDIAN_API_KEY
ENV VITE_APP_NYT_API_KEY=$VITE_APP_NYT_API_KEY

CMD ["npm", "run", "dev"]
